### ISSUE TITLE
Add Views relationships (both forward and reverse)

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/reference#21]
I'm trying to display a block with 'reverse' links to a referencing node. My post type has a reference field, and Article A displays a reference link to Article B, C, and D.

On Article B, C, and D I want to display a reverse link to Article A. As far as I remember from Drupal and Entity Reference, it was possible to use a relationship called "Referencing Entity". Using *Reference* I can't find this relation in Views, but only a "referenced by" relationship (e.g. *Node referenced by field_post_related*). I propose to add the "referencing" relationship as well.

Forward relationships `Reference to`:

`Node 1 -> node 2`

Reverse relationships `Reference from`:

`Node 2 <- node 1`

---
~Merged PR: https://github.com/backdrop-contrib/reference/pull/47~

**Comment by olafgrabienski** [comment]
I just checked the [References](https://github.com/backdrop-contrib/references) module and saw that it provides a Views relationship for a referencing field, see the following screenshot:

![screen-backdrop-references-views-referencing](https://user-images.githubusercontent.com/14188307/27044794-299cefb8-4f9f-11e7-9bcd-cf8f9df6de59.png)

I tested the functionality quickly, and it works fine. I understood that one goal of *Reference* is to replace *References* and similar contrib modules in core. So I'm hoping that my current request is within the goal of *Reference*. What do you think, @mikemccaffrey ?

**Comment by jenlampton** [comment]
I just added the reverse relationship.

**Comment by olafgrabienski** [comment]
Great! Do you think the PR is ready for testing?

**Comment by jenlampton** [comment]
Yes please :)

**Comment by olafgrabienski** [comment]
Hm, I've downloaded the ZIP from https://github.com/jenlampton/reference/tree/21-views-relationships to a quite fresh Backdrop site and tried to enable the module, but after hitting "Save configuration" I see an empty white page instead of the confirmation page. When I navigate to other pages by typing another URL, everything seems fine, and when I turn back to the Modules list page, the *Reference* module isn't enabled.

Before, on another test site, I replaced the folder of the *Reference* beta release by the `21-views-relationships` branch while the module was enabled. In this case, I got a white screen on several admin pages.

**Comment by olafgrabienski** [comment]
Today I've tried once more to install and enable the ZIP from https://github.com/jenlampton/reference/tree/21-views-relationships on a Backdrop site but I got the same result: After installation I tried to enable the module and got an empty white page instead of the confirmation page, and the module wasn't enabled. There were no errors in DBlog. @jenlampton does it work for you?

**Comment by jenlampton** [comment]
@olafgrabienski I had been using the patch on a site with the module already enabled. When I attempted to enable this on an existing site, I also got a fatal error:
```
Fatal error: Cannot redeclare reference_field_views_data() (previously declared in reference.module:444) in reference.module on line 491
```
I've fixed this and pushed an update to the PR. Feel free to test again when ready :)

**Comment by olafgrabienski** [comment]
@jenlampton I'm still without luck, not sure if I'm doing things right. I have

- installed the Reference module on a test site today, using the ZIP from https://github.com/jenlampton/reference/tree/21-views-relationships,
- added a Reference field to content type Page,
- created a Page with some references.

Finally, I created a View of posts with fields and tried to add a Relationship of "referencing" content. It wasn't available (there was only the relationship of "referenced" content).

Did I miss something?

**Comment by jenlampton** [comment]
> It wasn't available (there was only the relationship of "referenced" content).

You're right. It looks like the PR in https://github.com/backdrop-contrib/reference/pull/47 only includes forward relationships right now. I wonder what happened. I must have lost the reverse ones somewhere along the way. Let me check and see which site I was working with on Jun 24, 2019, and see if the module there still contains the reverse relationship. 

I'm going to merge the forward ones in the current PR so I can make an initial release.

**Comment by hosef** [comment]
I made a PR that should fix the ability to add a views relationship based on back references.

**Comment by olafgrabienski** [comment]
@hosef Great, I'd like to test it. Not sure where to find the code which includes the PR, can you point me to it?

**Comment by hosef** [comment]
@olafgrabienski Jen already merged the PR, so the latest dev release includes it.

**Comment by olafgrabienski** [comment]
Works for me! Here's how I've tested:

- installed the current dev version,
- added a *Reference* field to content type Page,
- created a Page, and referenced a Post,
- created a View of Posts with fields, and was able to add a "Reference from" Relationship
  - Name / Setting link: Reference: Reference from
  - Description: A bridge to the Content that has Content in its *field field_page_reference_post*
  - Identifier: Content referencing Content from field_page_reference_post)

**Comment by jenlampton** [comment]
Thank you @hosef !!! 

I'm going to close this issue then?
