### ISSUE TITLE
Comment link goes to root

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/reference#3]
On display the comment link goes to root, not to the referenced comment as expected.

![hbhb backdrop localhost](https://cloud.githubusercontent.com/assets/1042283/19502579/940fdda6-9573-11e6-8e06-e3a464b22913.png)

**Comment by olafgrabienski** [comment]
File reference goes to root as well:

![screen-backdrop-reference-file](https://cloud.githubusercontent.com/assets/14188307/19539217/861b41dc-9658-11e6-97e8-f4c1273abac8.png)

**Comment by olafgrabienski** [comment]
Some additional information: When I enable errors, I see the following messages related to comment reference:

> Notice: Undefined property: Comment::$path in reference_link_formatter_view() (line 165 of /.../modules/reference/reference.module).

And, probably related to file reference:

> Notice: Undefined property: File::$path in reference_link_formatter_view() (line 165 of /.../modules/reference/reference.module).

**Comment by mikemccaffrey** [comment]
Okay, the formatter uses this code to create the link:
`'#markup' => l($target_entity->$target_label_property, $target_entity->path['source']),`

It seems like the entity->path is not set for all the entity types.

**Comment by mikemccaffrey** [comment]
Alright, I've rewritten reference_link_formatter_view to properly format urls:
https://github.com/backdrop-contrib/reference/commit/83ed6a7124547e164dbc554a9104cbcb25f04461
