### ISSUE TITLE
PHP fatal when viewing a taxonomy term

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/reference#32]
When I view a taxonomy term I see the following:
```
Fatal error: Call to a member function uri() on a non-object in backdrop/modules/contrib/reference/reference.module on line 226
```

**Comment by mikemccaffrey** [comment]
I merged the pull request in, since it seems like a good check to make sure that the entity is loaded.

However, what was causing the taxonomy term not to load? We should probably solve that issue more directly.

**Comment by jenlampton** [comment]
This was previously a term-reference field on a different term ("related categories") so it might not be a common use-case. I suspect that the field was holding a value for a term that had been deleted, since editors did a bunch of "cleanup" on this site before it was upgraded into Backdrop.
