### ISSUE TITLE
Can we get a release (even beta) that shows up in b.org and in the Project Browser?

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/reference#37]
Searching for "reference" right now returns a whole lot of results, but not this module here. We need some exposure if more people are to test this in order to eventually get it into core.

There currently seems to be a beta1 release: https://github.com/backdrop-contrib/reference/releases

Any clues as to why it is not shown in [b.org](https://backdropcms.org/modules?s=reference) or the Project Browser?

<img width="901" alt="screen shot 2018-07-10 at 2 06 54 am" src="https://user-images.githubusercontent.com/2423362/42462224-ff727772-83e5-11e8-809f-745ff1966d8a.png">

**Comment by alexfinnarn** [comment]
Doesn't it have to be `1.x-1.0.0-beta1` to follow the semantic versioning? I will try and test this module out some, but if it works well enough, why not just make a release and leave the note about being in beta mode? I don't know of any other Backdrop modules in beta to compare the versioning to at the moment.

**Comment by mikemccaffrey** [comment]
@klonos I don't know what it will take to get the release to appear on the backdrop site. @jenlampton would have a better idea. I think she mentioned that she would look into it before, but I forget how we left things.

I can switch to the semantic versioning with the first full release, assuming that we are following that numbering system for contrib modules in addition to core.

**Comment by jenlampton** [comment]
In order for References to appear in the project browser (and on b.org) it needs to have a stable release (so 1.x-1.0.0).

**Comment by laryn** [comment]
I think we have a release now, so I'm closing this.
