### ISSUE TITLE
mismatched entity label reference

### ISSUE THREAD

**Issue by bradbulger** [backdrop-contrib/reference#43]
In reference_field_settings_form()

```php
if (isset($entity_type_info['keys']['label'])) {
      $entity_type_options[$entity_type] = $entity_type_info['label'];
```

I believe it's just [label] - that's what the core entity definitions look like to me, anyway. Paragraphs was failing the check for [keys][label] for example. It should be consistent in any case.

**Comment by jenlampton** [comment]
The current head uses `if (isset($entity_type_info['entity keys']['label'])) {` now instead. 

I'm going to make an initial release. Please test that and if the problem still occurs with paragraphs, please re-open this issue :)
