### ISSUE TITLE
Support entity reference revisions.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/reference#7]
There is the [Entity Reference Revisions](https://www.drupal.org/project/entity_reference_revisions) contrib module that:

> When the parent entity is updated, the referenced entity is also updated, thus the previous revision of the parent entity should still be pointing to the previous version of the entity to fully support revision diff and rollback.

I think we should support this, although not entirely sure that the way this specific module goes about doing it is the right way to do it.

**Comment by mikemccaffrey** [comment]
The vast majority of sites are likely looking to just reference the current version of an entity, so we are probably not looking to support reference revisions in core, and this should continue to be a contrib module.

Make sense?

**Comment by klonos** [comment]
I guess yes. I can't remember the specific use case I had in mind when I filed this.
