### ISSUE TITLE
README.md needs updating. 

### ISSUE THREAD

**Issue by ericfoy** [backdrop-contrib/reference#75]
Since Backdrop has obviously pursued a different path to the one described in the README, with regard to moving this module into core, I think some edits are in order to avoid misleading anyone...

**Comment by stpaultim** [comment]
I submitted a quick and dirtly PR to remove the information in the README that suggests that this module will be included in core, which is no longer the case.

@jenlampton

**Comment by olafgrabienski** [comment]
Maybe also mention that Entity Reference isn't enabled by default (so far).

**Comment by stpaultim** [comment]
@olafgrabienski Thanks. I modified my PR.
