### ISSUE TITLE
Examine how D8 handles the creation of new referenced taxonomy term entities in the tags autocomplete field.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/reference#8]
It was mentioned in today's meeting that if we are to change the taxonomy term fields to be entity reference fields (once Reference module is in core - 1.6.0 hopefully), then we'd face the following issue... These fields are autocomplete, but if you type in something that is not already an existing term, then that action would (in the background) trigger the creation of a new term before finally adding the reference to it. I just double-checked and in D8 (in which terms are referenced entities) that feature is still present. Perhaps see how what they have done to solve this problem?

**Comment by mikemccaffrey** [comment]
Closing in favor of issue #30.
